### ISSUE TITLE
Few suggestions 

### ISSUE THREAD

**Issue by ghost** [drzaiusx11/create-oi#1]
Hi, I got iCreate2 recently, I pulled down your respository (very good work) and I noticed that the BAUD RATE is hardcoded to 57600 whereas the iRobot create2 default baud is 115200

```
        serial = new SerialPort(settings.serialport, { baudrate: 57600, bufferSize: 5 });

to 

     serial = new SerialPort(settings.serialport, {
            baudrate: (typeof settings.baudrate === 'undefined') ? 57600 : settings.baudrate,
            bufferSize: 5
        });  
```

Can you use the init settings to pass it as parameter rather than hardcoding it? I modified locally and it works, if you are okay I can contribute to your project 

I am planning provide functions to program songs etc, I can add it if you make me a contributor 

Regards
GOPI

**Comment by drzaiusx11** [comment]
Hi GOPI, 

Thanks for the suggestions! I've added you as a collaborator to the project, so feel free to add create2 support (I don't have access to a create2 atm.)

Jeff

**Comment by etoxin** [comment]
Hey, same boat. I'll create a pull request soonish

**Comment by drzaiusx11** [comment]
setting { version: 2 } in init() now properly handles the Create2
