### ISSUE TITLE
Doesn't Work with recent serialport

### ISSUE THREAD

**Issue by mmccool** [drzaiusx11/create-oi#9]
This library does not work with current versions of serialport.   I've found a fix (just use `require("serialport")` instead of `require("serialport").SerialPort`) and will shortly be submitting a PR.   But then the fix should be propagated up to npm, and to avoid future breaking changes the dependency given in package.json should probably be more restrictive.

**Comment by drzaiusx11** [comment]
removed the .SerialPort
